# -*- coding: utf-8 -*-
"""Exercise 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10W7K-orywCPoVaGpcieG3eiiq2HrisSM

#Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

Some of the popular languages that Data Scientists use are:

1.   R
2.   C++
3.   Python

Some of the commonly used libraries used by Data Scientists include:

1.   TensorFlow
2.   NumPy
3.   tidyverse

# Data Science Tools

| Tool          |
|----------------|
| VsCode       | IDE      | Interactive development environment for Python, often used for data analysis and scientific computing. |
| Atom       | IDE      | IDE for R programming, popular in statistics and data science. |
| Tableau       | Tool     | A powerful data visualization tool used in the Business Intelligence Industry for data analysis. |
| Power BI      | Tool     | A business analytics service by Microsoft that provides interactive visualizations and business intelligence capabilities with an interface simple enough for end users to create their own reports and dashboards. |

### Below are a few examples of evaluating arithmetic expressions in Python
"""

#This a simple arithmetic expression to mutiply then add integers.
print((3*4)+5)

minutes = 200
hours = minutes / 60
print(f"This will convert {minutes} minutes to hours by dividing by 60.")
print(hours)

"""**Objectives:**

* List popular data languages.
* Do a simple arithmetic expression.
* Convert minutes to hours

## Author
Diana Laura López Huerta
"""