# -*- coding: utf-8 -*-
"""Exercise 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10W7K-orywCPoVaGpcieG3eiiq2HrisSM

# DataSchool

This noteboook contains information on the course you will be attending. Please read carefully.

Languages


1.   R
2.   C++
3.   Python

Libraries


1.   TensorFlow
2.   NumPy
3.   tidyverse

| Tool          | Type     | Description                                             |
|---------------|----------|---------------------------------------------------------|
| Jupyter       | IDE      | Interactive development environment for Python, often used for data analysis and scientific computing. |
| RStudio       | IDE      | IDE for R programming, popular in statistics and data science. |
| Tableau       | Tool     | A powerful data visualization tool used in the Business Intelligence Industry for data analysis. |
| Power BI      | Tool     | A business analytics service by Microsoft that provides interactive visualizations and business intelligence capabilities with an interface simple enough for end users to create their own reports and dashboards. |

# Arithmetic Expression Examples
This is what you will learn on the course.
"""

print(4*2)
print(2+3)
print(5+7)

minutes = 120
hours = minutes / 60
print(f"{minutes} minutes is {hours} hours.")

"""# Objectives
This is a summary of what you will be learning on the course.



* Manage data
* Data Cleaning
* Data Mining

## Author
- Name: Diana Laura López Huerta
- Location: Monterrey, México
"""